### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by tommygebru** [nikifoth/prj-rev-bwfs-dasmoto#2]
https://github.com/nikifoth/prj-rev-bwfs-dasmoto/blob/6ce11a8dd7cce6bcd42e819b6c9bd7ea07c52545/Dasmotos/resources/style.css#L9

background image is using a web address instead of local images and a local file path, as you practiced in your html page

You can review file paths and linking documents here 👍 
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files

https://www.kirupa.com/html5/all_about_file_paths.htm

**Comment by nikifoth** [comment]
Fixed in commit 976078b548d6da3aec56d5a61b10af6cbdd1931d
