### ISSUE TITLE
Dont Repeat Yourself (or DRY method)

### ISSUE THREAD

**Issue by tommygebru** [nikifoth/prj-rev-bwfs-dasmoto#4]
Consider applying css styles to the html elements once, instead of having to write out the font-weight tags in your css document multiple times. 

for example
```
h1, h2, .price {
font-weight: bold;
}
```

The font-weight property could be assigned to the entire page with the html tags, as you've done for the font-family 👍 

Also you can probably use the span selector, instead of creating a new classname `price`

**Comment by nikifoth** [comment]
Refactored html and css in commit f18bd01cde8b247059fcf474c9bc427654cfeb43
