### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tommygebru** [nikifoth/prj-rev-bwfs-dasmoto#6]
Overall Exceeds Expectations!
Hey Nikifoth great work on your project Dasmotos 
About Linking:
Looking over your code I can see that you used good html structure as well as css.
Your css is linked to the html page and uses an appropriate file path. Your background image should also be linked locally, so that file assets are always accessible to your user. 

About Structure:
Your documents both have good hierarchy for the page structure, your css is a cascading stylesheet, so anything written at the bottom of the page will be applied/recognized and therefore overriding a previous style written above it.

The html structure
Cool use of divs to group smaller and appropriately sectioned elements. This is known as nesting elements within the parent, or wrapping children elements within a container.

About Syntax:
Syntax is our grammar and spelling of code, if there are any errors in your code it would show in your browser and can negatively affect the desired outcome. There were little to no errors in your code but i encourage you to always take more time to revise for errors (code checking is how we spend half our time 😆 ).

Ok - Great work overall Nikifoth  I suggested some things to bookmark or simply keep in mind to improve your project:
For your editor of choice, include a linter extension or plugin (a syntax-checker) for your coding language, this will save you hours if not days of work!! 😋

Lastly keep some HTML/CSS best practices in mind when coding
https://www.codecademy.com/articles
When in doubt Google it (or MDN it) 🎉

**Comment by nikifoth** [comment]
Thanks for your feedback tommygebru! I've taken your suggestions on board and implemented any fixes/enhancements accordingly.

**Comment by tommygebru** [comment]
Of course Nikifoth 👌 keep up the good work and happy coding !
